# Generated by Django 6.0.2 on 2026-02-19 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=18)),
                ('level', models.IntegerField(default=1)),
                ('xp', models.CharField(default='0/5000', max_length=20)),
                ('events_count', models.IntegerField(default=0)),
                ('hours_count', models.IntegerField(default=0)),
                ('friends_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=5.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
