# Generated by Django 6.0.2 on 2026-02-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_skilltag_helperreview_review_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва бейджа (напр. 🌿 еко)'),
        ),
    ]
