# Generated by Django 6.0.2 on 2026-02-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_skilltag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helperreview',
            name='review_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AlterField(
            model_name='helperreview',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='helperreview',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skilltag',
            name='color',
            field=models.CharField(default='#14532d', max_length=20, verbose_name='Колір (HEX)'),
        ),
        migrations.AlterField(
            model_name='skilltag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва бейджа'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(default='Новачок', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Години'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
