# Generated by Django 6.0.2 on 2026-02-25 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_helperreview_review_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='helperreview',
            name='review_type',
            field=models.CharField(choices=[('helper', 'Як помічнику'), ('organizer', 'Як організатору')], default='helper', max_length=20, verbose_name='Тип відгуку'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вік'),
        ),
        migrations.AlterField(
            model_name='helperreview',
            name='rating',
            field=models.IntegerField(default=5, verbose_name='Оцінка (1-5)'),
        ),
        migrations.AlterField(
            model_name='helperreview',
            name='text',
            field=models.TextField(verbose_name='Текст відгуку'),
        ),
        migrations.AlterField(
            model_name='skilltag',
            name='color',
            field=models.CharField(default='#14532d', max_length=20, verbose_name='Колір фону (HEX)'),
        ),
        migrations.AlterField(
            model_name='skilltag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва бейджа (напр. 🌿 активний)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(default='Новачок', max_length=50, verbose_name='Рівень'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Години (XP)'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва події')),
                ('description', models.TextField(verbose_name='Опис')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг події')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
