# Generated by Django 6.0.2 on 2026-02-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_helperreview_review_type_userprofile_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skill_tags',
        ),
        migrations.RemoveField(
            model_name='helperreview',
            name='review_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.DeleteModel(
            name='SkillTag',
        ),
    ]
