# Generated by Django 6.0.2 on 2026-02-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва бейджа (напр. 🌿 активний)')),
                ('color', models.CharField(default='#14532d', max_length=20, verbose_name='Колір фону (HEX)')),
            ],
        ),
        migrations.AddField(
            model_name='helperreview',
            name='review_type',
            field=models.CharField(choices=[('helper', 'Як помічнику'), ('organizer', 'Як організатору')], default='helper', max_length=20, verbose_name='Тип відгуку'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill_tags',
            field=models.ManyToManyField(blank=True, to='users.skilltag', verbose_name='Бейджі під аватаркою'),
        ),
    ]
