# Generated by Django 6.0.2 on 2026-02-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_skilltag_helperreview_review_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='required_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Потрібно годин (XP)'),
        ),
    ]
