# Generated by Django 6.0.2 on 2026-02-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_event_date_event_end_time_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.TextField(blank=True, null=True, verbose_name='Програма або план дій'),
        ),
        migrations.AddField(
            model_name='event',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Що взяти з собою? (кожний пункт з нового рядка)'),
        ),
    ]
