# Generated by Django 6.0.2 on 2026-03-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_event_program_event_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='users.userprofile', verbose_name='Друзі'),
        ),
    ]
