# Generated by Django 6.0.2 on 2026-02-19 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('category', models.CharField(max_length=100, verbose_name='Категорія')),
                ('work_type', models.CharField(max_length=100, verbose_name='Тип роботи')),
                ('duration', models.CharField(max_length=50, verbose_name='Тривалість')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
        ),
    ]
