# Generated by Django 6.0.2 on 2026-02-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_badge_event_helperreview_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вік'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.CharField(default='Новачок', max_length=50, verbose_name='Рівень'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Години (XP)'),
        ),
    ]
