# Generated by Django 6.0.2 on 2026-03-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_userprofile_friends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL аватара (Supabase)'),
        ),
    ]
