# Generated by Django 6.0.2 on 2026-03-03 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0003_event_is_completed'),
        ('users', '0019_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='mapapp.event'),
        ),
    ]
