# Generated by Django 6.0.2 on 2026-03-03 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0004_eventreview'),
        ('users', '0021_remove_event_event_helperreview_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperreview',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper_reviews', to='mapapp.event'),
        ),
    ]
